hosts:
  web:
    ansible_host: 34.121.30.18
    ansible_become_user: root
    ansible_connection: ssh
    ansible_ssh_private_key_file: "~./.ssh/id_rsa"
    ansible_become_password: $HOST_USER_PASSWORD