services:
  client-nginx:
    image: registry.gitlab.com/locksley-w4/watchstore-webapp/client:latest
    environment:
      - NODE_ENV=production
    ports:
      - 80:80

  api:
    image: registry.gitlab.com/locksley-w4/watchstore-webapp/api:latest
    env_file:
      - .env
    expose:
      - 5000
    restart: always
