services:
  client:
    image: registry.gitlab.com/locksley-w4/watchstore-webapp/client
    environment:
      - NODE_ENV=production

  api:
    image: gistry.gitlab.com/locksley-w4/watchstore-webapp/api
    expose:
      - 5000
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - client-build:/usr/share/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      client-builder:
        condition: service_completed_successfully
      api:
        condition: service_started

volumes:
  client-build: